# dev mode
services:
  order-service:
    build: 
      context: ./orders
      dockerfile: ./Dockerfile
    command: bash -c "go run ./migrate/migrate.go && go run ./main.go"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_USER: tucows
      POSTGRES_PASSWORD: abacus123
      POSTGRES_DB: tucows
      POSTGRES_DB_PORT: 5432
    networks:
      - tucows-network
      
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tucows
      POSTGRES_PASSWORD: abacus123
      POSTGRES_DB_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tucows -U tucows"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - tucows-network

volumes:
  postgres-vol:

networks:
  tucows-network:
    driver: bridge
