# dev mode
services:
  order-service:
    restart: on-failure
    build: 
      context: ./orders
      dockerfile: ./Dockerfile
    command: bash -c "go run ./migrate/migrate.go && go run ./main.go"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    links:
      - postgres
      - rabbitmq
    ports:
      - '8080:8080'
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_USER: tucows
      POSTGRES_PASSWORD: abacus123
      POSTGRES_DB: tucows
      POSTGRES_DB_PORT: 5432
      REQUEST_QUEUE: paymentreq
      RESPONSE_QUEUE: paymentresp
      RABBITMQ_CONN_STRING: amqp://guest:guest@rabbitmq:5672/
    networks:
      - tucows-network
  
  payments-service:
    restart: on-failure
    build: 
      context: ./payments
      dockerfile: ./Dockerfile
    command: go run ./main.go
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      REQUEST_QUEUE: paymentreq
      RESPONSE_QUEUE: paymentresp
      RABBITMQ_CONN_STRING: amqp://guest:guest@rabbitmq:5672/
    networks:
      - tucows-network
  
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - rabbitmq-vol:/var/lib/rabbitmq
    networks:
      - tucows-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: tucows
      POSTGRES_PASSWORD: abacus123
      POSTGRES_DB_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tucows -U tucows"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - tucows-network

volumes:
  postgres-vol:
  rabbitmq-vol:

networks:
  tucows-network:
    driver: bridge
