package utils

type PAYMENT_STATUS string
type ORDER_STATUS string

const (
	ORDER_STATUS_PAYMENT_PENDING ORDER_STATUS = "PAYMENT_PENDING"
	ORDER_STATUS_PROCESSING      ORDER_STATUS = "PROCESSING"

	PAYMENT_STATUS_PENDING PAYMENT_STATUS = "PENDING"
	PAYMENT_STATUS_PAID    PAYMENT_STATUS = "PAID"
	PAYMENT_STATUS_FAILED  PAYMENT_STATUS = "FAILED"
)
